name: backend  
on:  
  push: 
    branches:
      -main
  

jobs:
  myprojectdeploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git library
       uses: actions/checkout@v4
      - name: connection
      uses: appleboy/ssh-action@v1.2.0
      
with:
   host: ${{secrets.IP}}
   username: ${{secrets.USERNAME}}
  password: ${{secrets.PASSWORD}}
        
script: |
  cd /home/palak/seedly_bcknd
  git pull origin main 
  npm i
  npm start
  pm2 start index.js --name "backend"
